AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to deploying a simple s3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: DOC-EXAMPLE-BUCKET
  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Resource: 'arn:aws:s3:::DOC-EXAMPLE-BUCKET'
            Principal: '*'
            Condition:
              ArnEquals:
                "aws:PrincipalArn": "arn:aws:iam::444455556666:root"